### ISSUE TITLE
Evaluation metrics vary a lot from dataset from dataset

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#659] opened 2023-10-25 13:49 UTC
Hi @miguelriemoliveira,

Do you know why the evaluation is so different from one dataset to another when the datasets are from the same bag? This makes no sense whatsoever to me 

`rosrun atom_evaluation rgb_to_rgb_evaluation -train_json /home/daniela/datasets/larcc_subset/real/train/atom_calibration.json -test_json /home/daniela/datasets/larcc_subset/real/test/dataset_corrected.json -ss rgb_camera_3 -st hand_camera_rgb`

```
+--------------+-----------+-------------+-------------+------------+-----------+
| Collection # | RMS (pix) | X err (pix) | Y err (pix) | Trans (mm) | Rot (deg) |
+--------------+-----------+-------------+-------------+------------+-----------+
|     000      |  13.3731  |   12.8433   |    3.4592   |  50.9878   |   4.8143  |
|     001      |  12.9329  |   12.4168   |    3.4694   |  32.3980   |   2.4888  |
|     002      |  12.6282  |   12.2616   |    2.8255   |  50.8385   |   5.1259  |
|     003      |   4.6824  |    3.4327   |    1.8146   |  51.1020   |   2.6548  |
|     004      |   3.6803  |    2.1332   |    2.3391   |  34.1847   |   2.5086  |
|   Averages   |   9.4594  |    8.6175   |    2.7816   |  43.9022   |   3.5185  |
+--------------+-----------+-------------+-------------+------------+-----------+
```

`rosrun atom_evaluation rgb_to_rgb_evaluation -train_json /home/daniela/datasets/larcc_subset/real/train/atom_calibration.json -test_json /home/daniela/datasets/larcc_subset/real/train_small/dataset_corrected.json -ss hand_camera_rgb -st rgb_camera_3 `

```
+--------------+-----------+-------------+-------------+------------+-----------+
| Collection # | RMS (pix) | X err (pix) | Y err (pix) | Trans (mm) | Rot (deg) |
+--------------+-----------+-------------+-------------+------------+-----------+
|     000      |  192.3300 |   182.5350  |   58.1402   |  342.7835  |   4.8552  |
|     001      |  189.7554 |   180.4850  |   57.6143   |  339.2840  |   3.3166  |
|     002      |  188.6738 |   180.2046  |   53.8624   |  343.1277  |   5.5344  |
|     005      |  65.3254  |   64.6120   |    7.7481   |  247.7729  |   7.7724  |
|     006      |  71.4563  |   62.9036   |   31.9909   |  242.1490  |   7.5084  |
|   Averages   |  141.5082 |   134.1480  |   41.8712   |  303.0234  |   5.7974  |
+--------------+-----------+-------------+-------------+------------+-----------+
```

**Comment by danifpdra** [comment] 2023-10-25 13:56
BTW, the errors that came from the calibrate script are much much lower but the evaluations are still super high. I don't understand anything

**Comment by miguelriemoliveira** [comment] 2023-10-25 14:19
Hi @danifpdra ,

for me it will be difficult to look into this until the weekend.

Perhaps @manuelgitgomes has some insight ...

**Comment by manuelgitgomes** [comment] 2023-10-25 14:46
Hello @danifpdra and @miguelriemoliveira 

> the errors that came from the calibrate script are much much lower but the evaluations are still super high

This seems to me like the optimization process landed on a local minimum.
Visualize the results of the calibration.
If something seems wrong, maybe try another initial estimate.

> Do you know why the evaluation is so different from one dataset to another when the datasets are from the same bag? This makes no sense whatsoever to me

Regarding this, try and visualize the results of the evaluation.
If the system is indeed on a local minimum, one dataset might favor that minimum when compared to another.

**Comment by danifpdra** [comment] 2023-10-25 14:50
Hi @manuelgitgomes ,

I already did that and the results seem ok to me... 
![image](https://github.com/lardemua/atom/assets/47574905/5794e870-addf-4e0f-a61d-8d55b22d4aef)

**Comment by miguelriemoliveira** [comment] 2023-10-26 17:46
Hi @danifpdra ,

I am wondering about the tables printed by each calibration during calibration. Can you put them here? 
That could give us a hint if the problem is related  to the evaluation or something more...

**Comment by miguelriemoliveira** [comment] 2023-10-26 17:57
> BTW, the errors that came from the calibrate script are much much lower but the evaluations are still super high. I don't understand anything

Wait, now I am reading this and this kind of answers my question. So that means the problem is only in the evaluation?

**Comment by danifpdra** [comment] 2023-10-26 18:02
> > BTW, the errors that came from the calibrate script are much much lower but the evaluations are still super high. I don't understand anything
> 
> Wait, now I am reading this and this kind of answers my question. So that means the problem is only in the evaluation?

I don't think so. When I calibrate just the two RGB cameras the evaluation still gives me like 10px of error. But I know the methodology works because I calibrated the simulated system and it works flawlessly

**Comment by miguelriemoliveira** [comment] 2023-10-26 18:42
> I don't think so. When I calibrate just the two RGB cameras the evaluation still gives me like 10px of error. But I know the methodology works because I calibrated the simulated system and it works flawlessly

I am confused, this points to the problem being in the evaluation, right? Am I misunderstanding?

**Comment by danifpdra** [comment] 2023-10-26 18:43
I don't think so. The evaluation works well with the simulated dataset

**Comment by miguelriemoliveira** [comment] 2023-10-27 08:01
Hum, but it can be something in the evaluation that only occurs with real data.

When you say: "But I know the methodology works because I calibrated the simulated system and it works flawlessly"
To me it seems that the calibration is working fine (I guess you see the error tables printed during calibration and they are fine), and the problem is in the evaluation. I am still lost.

Where do you think the problem is?

**Comment by danifpdra** [comment] 2023-10-27 09:06
I honestly don't know... Let's take this example evaluating the hand_camera_depth to rgb_camera_3 pairs.

Collection 000; RMS 5.32 - Seems fine

![image](https://github.com/lardemua/atom/assets/47574905/249381bb-f9c7-40d0-aac6-ec8001e98d3b)

Collection 016; RMS 9.46 - seems displaced

![image](https://github.com/lardemua/atom/assets/47574905/d61fad92-14d6-4bf2-af75-ebf5ed609a9c)

Collection 017; RMS 12.33

![image](https://github.com/lardemua/atom/assets/47574905/8fefb340-0826-4412-995a-00e9fcc6d4ff)

Evaluation seems to be matching the images, I think, but the errors are very high sometimes. In the same dataset I have RMS varying from 25 to 1 in difference collections 

And then in the RGB evaluation, all the values are very high and the evaluation is 57px...

![image](https://github.com/lardemua/atom/assets/47574905/704fefef-53be-4f09-93b6-bd4757a52c7f)

**Comment by manuelgitgomes** [comment] 2023-10-27 09:13
> Hum, but it can be something in the evaluation that only occurs with real data.

This seems unlikely to me, at least for the rgb to rgb evaluation, which has been the same since the beginning.

Does this only occur for sensors in the hand? Is the hand RGB-D corrected?

**Comment by danifpdra** [comment] 2023-10-27 09:14
> > Hum, but it can be something in the evaluation that only occurs with real data.
> 
> This seems unlikely to me, at least for the rgb to rgb evaluation, which has been the same since the beginning.
> 
> Does this only occur for sensors in the hand? Is the hand RGB-D corrected?

yes, one RGB and one depth in the hand. what do you mean corrected?

**Comment by manuelgitgomes** [comment] 2023-10-27 09:15
> yes, one RGB and one depth in the hand. what do you mean corrected?

The problem we had with RGB-D in the gantry. We changes the xacros to correct it.
Is it applied to the hand RGB-D?

**Comment by danifpdra** [comment] 2023-10-27 09:17
> > yes, one RGB and one depth in the hand. what do you mean corrected?
> 
> The problem we had with RGB-D in the gantry. We changes the xacros to correct it. Is it applied to the hand RGB-D?

I didn't know of any problem, but I used the set_initial_estimate to improve the first guess so it would eliminate that, no?

**Comment by miguelriemoliveira** [comment] 2023-10-27 18:46
Hi @danifpdra ,

I think I may have found the problem. When I refactored the pattern detection code some weeks ago I changed the coordinate system of the pattern.

![image](https://github.com/lardemua/atom/assets/11350998/b143d6df-980f-44ef-81c2-64d968f905fa)


Now the generation of the ground truth boundary  points used to compute the cost function is based on this coordinate frame. 

You can see in the image that the points are not well positioned, and I think that's the problem. I think all range sensors work fine because the error is like a bias  for all sensors, but in the case of the rgb sensor there is a clear inconsistency which should generate the high errors you refer.

I have no clue why it worked on simulation tough ...

I will continue to investigate.

Actually, now that I notice also the pattern corners are incorrectly placed.

I am really puzzled how and @manuelgitgomes  are getting good calibration results ...

**Comment by miguelriemoliveira** [comment] 2023-10-27 18:57
Fixed the generation of ground truth data:

![image](https://github.com/lardemua/atom/assets/11350998/80707acf-aaa4-4ae7-a72d-2f2065ee6b74)

I will now try to evaluate the impact ...

**Comment by miguelriemoliveira** [comment] 2023-10-28 08:18
Continuing on #663

**Closed as completed by miguelriemoliveira** 2023-10-28 08:18 UTC
Labels: bug, help wanted
