### ISSUE TITLE
Is RGB calibration really right? 

### ISSUE THREAD

**Issue by danifpdra** [lardemua/atom#675] opened 2023-11-08 17:40 UTC
I am getting weird calibration output errors for RGB pairs. Check more details on this issue https://github.com/danifpdra/rgbdbot/issues/2

**Comment by danifpdra** [comment] 2023-11-08 17:43
I am using a chessboard instead of a charuco... Could this be the problem? 

https://github.com/lardemua/atom/blob/8498653f755f7900e7b89dae35b7c638524bffb1/atom_calibration/src/atom_calibration/calibration/patterns_config.py#L230-L239

**Comment by miguelriemoliveira** [comment] 2023-11-08 19:25
Hum ... I think this is the problem I solved for the new opencv version in the rgb_labeler. 
Perhaps the problem is still there on the opencv calibration script

I will take a look tonight and try to call...

**Comment by danifpdra** [comment] 2023-11-08 22:56
Ok, let me know then

**Comment by miguelriemoliveira** [comment] 2023-11-08 23:29
Hi @danifpdra ,

Sorry, only now I am free and too sleepy to work. Lets talk tomorrow afternoon, ok?

Again sorry,
Miguel

**Comment by miguelriemoliveira** [comment] 2023-11-09 21:46
Lets work on #654 to see if chessboards work fine.

**Comment by miguelriemoliveira** [comment] 2023-11-14 16:41
@danifpdra can we close this?

**Comment by miguelriemoliveira** [comment] 2023-11-18 10:54
Closing for now.

**Closed as completed by miguelriemoliveira** 2023-11-18 10:54 UTC
Labels: bug
